name: dart
description: You don't need to be worried just because you have to support multiple screens
version: 2.1.47-beta.3f65115dd63b0b40ad027b653ab480416baf1356

homepage: https://github.com/DisplayKit/responsive_styles

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
