name: dart
description: You don't need to be worried just because you have to support multiple screens
version: 2.1.3-beta.93eade3561265d2685c0438475ef2e49edbd455e

homepage: https://github.com/DisplayKit/responsive_styles

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
