name: Release Package
on:
  push:
    branches:
      - main

env:
  GIT_AUTHOR_NAME: "@bumper-bot"
  GITHUB_TOKEN: ${{ secrets.GH_GLOBAL_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_GLOBAL_TOKEN || secrets.GH_GLOBAL_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Start: Unit Testing"
      run: |
        yarn install
        yarn test

  release:
    needs: 
      - test
    name: Release [JS NPM & GitHub Registry]
    runs-on: ubuntu-18.04
    steps:
      - name: Release NPM Registry
        run: |
          npm publish --token=${{ secrets.NPM_TOKEN }}
      - name: Release GitHub Registry
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' > ~/.npmrc
          yarn release:github_registry