name: Release Package
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_GLOBAL_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_GLOBAL_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    ## [Setup_CI]
    # ======================
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    # ======================
    - name: "Start: Unit Testing"
      run: |
        yarn install
        yarn test

  release:
    needs: 
      - test
    name: Release [JS NPM & GitHub Registry]
    runs-on: ubuntu-latest
    steps:
    ## [Setup_CI]
    # ======================
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    # ======================
    - name: Release NPM Registry
      run: |
        echo '//npm.pkg.github.com/:_authToken=${{ env.NPM_TOKEN }}' > ~/.npmrc
        npm publish --token=${{ env.NPM_TOKEN }} --access=public
    - name: Release GitHub Registry
      run: |
        echo '//npm.pkg.github.com/:_authToken=${{ env.GITHUB_TOKEN }}' > ~/.npmrc
        npm publish --@displaykit:registry=https://npm.pkg.github.com --force