name: PR comment
on:
  issue_comment:                                     
    types: [created, edited]

env:
  GITHUB_REPO_OWNER: "displaykit"
  GITHUB_REPO_NAME: "bump-release"
  GITHUB_PR_NUMBER: ${{ github.event.issue.number }}
  GITHUB_TOKEN: ${{ secrets.GH_GLOBAL_TOKEN }}
  COMMIT_EMAIL: "13791385+omariosouto@users.noreply.github.com"
  COMMIT_USERNAME: "CI Bot - DevSoutinho"

jobs:
  comment_checker:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      ## ==================

      - name: "[RELEASE]"
        if: contains(github.event.comment.body, '/release/') # support|major|minor|patch
        run: | 
          yarn install
          yarn setup
          git config --global user.email ${{ env.COMMIT_EMAIL }}
          git config --global user.name ${{ env.COMMIT_USERNAME }}
          bump-release ${{ github.event.comment.body }}
