name: PR comment
on:
  issue_comment:                                     
    types: [created, edited]

env:
  GITHUB_REPO_OWNER: "displaykit"
  GITHUB_REPO_NAME: "bump-release"
  GITHUB_PR_NUMBER: ${{ github.event.issue.number }}
  GITHUB_TOKEN: ${{ secrets.GH_GLOBAL_TOKEN }}
  COMMIT_USERNAME: "CI Bot - DevSoutinho"
  COMMIT_EMAIL: "13791385+omariosouto@users.noreply.github.com"

jobs:
  comment_checker:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} # or .head.ref for branch name
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      ## ==================

      - name: "[RELEASE]"
        if: contains(github.event.comment.body, '/release/') # support|major|minor|patch
        run: | 
          cat .git/HEAD
          yarn install && yarn setup
          git config --global user.name "${{ env.COMMIT_USERNAME }}"
          git config --global user.email ${{ env.COMMIT_EMAIL }}
          bump-release ${{ github.event.comment.body }}
