name: PR comment
on:
  issue_comment:                                     
    types: [created, edited]

env:
  GITHUB_REPO_OWNER: "displaykit"
  GITHUB_REPO_NAME: "bump-release"
  GITHUB_PR_NUMBER: ${{ github.event.issue.number }}
  GITHUB_TOKEN: ${{ secrets.GH_GLOBAL_TOKEN }}

jobs:
  comment_checker:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      ## ==================

      # Reference: https://github.com/devsoutinho/flutter-labs/blob/main/.github/workflows/releaser-bot.yml#L30
      - name: "[RELEASE]"
        if: contains(github.event.comment.body, '/release/') # support|major|minor|patch
        run: | 
          yarn install
          yarn setup
          bump-release ${{ github.event.comment.body }}